networks:
  spring_batch:
    driver: bridge

volumes:
  postgres-db:
    driver: local

services:
  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring_batch
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

