spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

psql-kyc:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: postgres
    dbSchema: KYC
    hikari:
      connection-timeout: 60000
      idle-timeout: 300000
      maximum-pool-size: 50
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl